_default:
    @just --choose

git:
    ssh kachi@ka.myvnc.com 'cd ~/.config/nvim && git pull'

test:
    XDG_CONFIG_HOME=.. nvim

dart-test:
    XDG_CONFIG_HOME=.. nvim .tests/test.dart

md-test:
    XDG_CONFIG_HOME=.. nvim .tests/test.md

dir-test:
    XDG_CONFIG_HOME=.. nvim .tests/

c-test:
    XDG_CONFIG_HOME=.. nvim .tests/test.c

rs-test:
    XDG_CONFIG_HOME=.. nvim .tests/test.rs

nix-test:
    XDG_CONFIG_HOME=.. nvim .tests/test.nix

html-test:
    XDG_CONFIG_HOME=.. nvim .tests/test.html

luau-test:
    XDG_CONFIG_HOME=.. nvim .tests/luau
