return {
	"folke/snacks.nvim",
	priority = 1000,
	event = "VeryLazy",
	opts = {
		bufdelete = { enabled = true },
		bigfile = { enabled = true },
		-- dashboard = { enabled = true },
		-- explorer = { enabled = true },
		input = { enabled = true },
		-- notifier = { enabled = true },
		dim = { enabled = true },
		picker = {
			enabled = true,
			layout = { preset = "ivy" },
		},
		quickfile = { enabled = true },
		scope = { enabled = true },
		-- scroll = { enabled = true },
		statuscolumn = { enabled = true },
		toggle = { enabled = true },
		words = { enabled = true },
		zen = { enabled = true },
	},
}
